// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolicitudesAPI.Models;

#nullable disable

namespace SolicitudesAPI.Migrations
{
    [DbContext(typeof(SistemaSolicitudesContext))]
    [Migration("20250410233644_redo")]
    partial class redo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolicitudesAPI.Models.Expediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ampliacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaPoseedoraInformacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CiudadSolicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cobro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComoDeseaRecibirRespuestaPersonaSolicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContenidoSolicitud")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("CorreoElectronicoSolicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosRecursoRevision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaLimitePrevencion10dias")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimiteRespuesta10dias")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimiteRespuesta20dias")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSesionComiteAmpliacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Materia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedioRecepcionSolicitudManual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MesAdmision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModalidadEntrega")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSolicitante")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroRecursoRevision")
                        .HasColumnType("int");

                    b.Property<int>("NumeroSesionComiteAmpliacion")
                        .HasColumnType("int");

                    b.Property<string>("PrecisionSentidoRespuesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Prevencion")
                        .HasColumnType("bit");

                    b.Property<int>("PromedioDiasRespuesta")
                        .HasColumnType("int");

                    b.Property<string>("RecibidaRegistrada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecursoRevision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentidoRespuesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubsanaPrevencionReinicoTramite")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SubsanaPrevencion_ReinicoTramite");

                    b.Property<string>("Tematica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TematicaEspecifica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDerecho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoSolicitud")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Solicitu__3214EC27AA69A3A2");

                    b.ToTable("Expedientes");
                });
#pragma warning restore 612, 618
        }
    }
}
